### ISSUE TITLE
Invoiceshelf cannot configure db connection after container is restarted

### ISSUE THREAD

**Issue by Lulu300** [InvoiceShelf/docker#17]
I've encoutered a major issue with the docker image. With at every image tags (latest, nightly and alpha) when i do the command `docker compose stop invoiceshelf` and then `docker compose start invoiceshelf`, invoiceshelf will nerver come back to life. When i check the logs here's what it says:
![image](https://github.com/user-attachments/assets/dfffbd0e-96aa-41a6-8ed8-19340e099960)

As long as i don't stop the container it works really great, but everytime I stop it I can't make it work again. The only solution to get it working again is to remove all volumes and reinstalling it again and again.

Here's my docker-compose.yml:

```YAML
services:
  ### BEGIN INVOICE CONTAINER ###
  invoice-pgsql:
    container_name: invoice-pgsql
    image: postgres:${INVOICE_PGSQL_VERSION}
    env_file:
      - ${INVOICE_PGSQL_ENV_FILE}
    volumes:
      - ${INVOICE_PGSQL_DATA_FOLDER}:/var/lib/postgresql/data
    secrets:
      - invoice_pgsql_password
    networks:
      invoice:
        ipv4_address: X.X.X.X
    restart: unless-stopped

  invoice:
    image: invoiceshelf/invoiceshelf:${INVOICE_VERSION}
    container_name: invoice
    hostname: invoice
    user: root
    env_file:
      - ${INVOICE_ENV_FILE}
    volumes:
      - ${INVOICE_CONFIG_FOLDER}:/conf
      - ${INVOICE_DATA_FOLDER}:/data
      # - ${INVOICE_HTML_FOLDER}:/var/www/html
    secrets:
      - invoice_pgsql_password
      - mail_noreply_password
    networks:
      swag:
        ipv4_address: X.X.X.X
      invoice:
        ipv4_address: X.X.X.X
    restart: unless-stopped
    depends_on:
      - invoice-pgsql
  ### END INVOICE CONTAINER ###
networks:
  swag:
    name: swag
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.1.0/24
         gateway: 172.18.1.1
  invoice:
    name: invoice
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.14.0/24
         gateway: 172.18.14.1
secrets:
  ### BEGIN MAIL_NOREPLY SECRETS ###
  mail_noreply_password:
    file: .secrets/mail_noreply_password.txt
  ### END MAIL_NOREPLY SECRETS ###
  ### BEGIN INVOICE SECRETS ###
  invoice_pgsql_password:
    file: .secrets/invoice_pgsql_password.txt
  ### END INVOICE SECRETS ###
```

Here's my env file for the invoicehself container (I've just replaced my real domain name by https://invoice.example.com):

```ENV
PHP_TZ=Europe/Paris
TIMEZONE=Europe/Paris
APP_NAME=Laravel
APP_ENV=local
APP_DEBUG=true
APP_URL=https://invoice.example.com
DB_CONNECTION=postgres
DB_HOST=invoice-pgsql
DB_PORT=5432
DB_DATABASE=invoice
DB_USERNAME=invoice
DB_PASSWORD_FILE=/run/secrets/invoice_pgsql_password
CACHE_STORE=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=invoice.example.com
SANCTUM_STATEFUL_DOMAINS=invoice.example.com
STARTUP_DELAY=2
MAIL_DRIVER=smtp
MAIL_HOST=${MAIL_NOREPLY_HOST}
MAIL_PORT=${MAIL_NOREPLY_SMTP_PORT}
MAIL_USERNAME=${MAIL_NOREPLY_USER}
MAIL_PASSWORD_FILE=${MAIL_NOREPLY_PASSWORD_FILE}
MAIL_ENCRYPTION=TLS
```

I hope this is enough information for you to see what's happening
