### ISSUE TITLE
Installation problem: Domain verification failed. Please enter valid domain name.

### ISSUE THREAD

**Issue by usersina** [InvoiceShelf/docker#21]
I want to install InvoiceShelf using the docker method. I want to have it running on `http://localhost:8888`.

However, I have this error:

![image](https://github.com/user-attachments/assets/1b5786f9-19f8-48b2-bf2c-f3f4e17e10f6)

Here's more information about the request that failed:

<details>
    <summary>Request Headers</summary>

```
GET /api/v1/auth/check HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7
Connection: keep-alive
Cookie: BBLANG=en_US; XSRF-TOKEN=eyJpdiI6IkZaejZnd3c4Z0JSM05KMVBqWndQWHc9PSIsInZhbHVlIjoiTjhHdVliYVBLSFJydHVteTd0cWtQWUlqMmUvSityU1ZudENwYVZBMUFMdS92U3NoMkZMRkwvbUNXSkhNaG1NaW1ScHRlZVN2MFJjemJuRlNSRExKQXRNeWpmcWV2d0lLTS83NzdKbUpJTWRaTU5KREV4bWxQMHZpY0RaN3F0SkUiLCJtYWMiOiJmZjNjNDM5MDM5ZGE2ZmE4N2IxY2E3YzM3YTg3ZjkxMDA4NWU4ZTMwMTlmNjdmMWVjYTRmNWZhMmZmMjM5NzI5IiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6InQ4ZFVTL01ObzRqRXpIOWl5enV0SVE9PSIsInZhbHVlIjoiZmVBaU1WWXR0U2lTaWQxRkI4bm5LeklZYnlOQ2pqTGpOR0xOZkZWYzFhTFhDWjRGdU5DaitYTUx0K1ZHMk1kRzMvczJoT1F6NGk3anlRbk0zK3FyQ2tYdmpjSEJod3d4VXQvOWZOMDJtNldoMWRBMW04R2lmMU1najJiYVFXY1YiLCJtYWMiOiIxZTQ5ZDI2Njg4ZDgwMDVlM2YzMWYzNmIxZmRlMDhlMmYwMzk1MDBhYzg4YTU0OGFiMGI4MDc3NDFiOGY2MWFiIiwidGFnIjoiIn0%3D
Host: localhost:8888
Referer: https://rdbzn5g96jx.typeform.com/to/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest
X-XSRF-TOKEN: eyJpdiI6IkZaejZnd3c4Z0JSM05KMVBqWndQWHc9PSIsInZhbHVlIjoiTjhHdVliYVBLSFJydHVteTd0cWtQWUlqMmUvSityU1ZudENwYVZBMUFMdS92U3NoMkZMRkwvbUNXSkhNaG1NaW1ScHRlZVN2MFJjemJuRlNSRExKQXRNeWpmcWV2d0lLTS83NzdKbUpJTWRaTU5KREV4bWxQMHZpY0RaN3F0SkUiLCJtYWMiOiJmZjNjNDM5MDM5ZGE2ZmE4N2IxY2E3YzM3YTg3ZjkxMDA4NWU4ZTMwMTlmNjdmMWVjYTRmNWZhMmZmMjM5NzI5IiwidGFnIjoiIn0=
company: 1
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
```

</details>

<details>
  <summary>Response Headers + Body</summary>

```
HTTP/1.1 401 Unauthorized
Server: nginx/1.22.1
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, private
Date: Sat, 28 Sep 2024 09:33:19 GMT
X-RateLimit-Limit: 180
X-RateLimit-Remaining: 178
Access-Control-Allow-Origin: *
```

```
{"message":"Unauthenticated."}
```

</details>

Here's my compose file:

```yml
services:
  invoiceshelf_db:
    container_name: invoiceshelf_db
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=somepass
      - POSTGRES_USER=invoiceshelf
      - POSTGRES_DB=invoiceshelf
    networks:
      - invoiceshelf
    restart: unless-stopped

  invoiceshelf:
    image: invoiceshelf/invoiceshelf:2.0.0
    container_name: invoiceshelf
    ports:
      - 8888:80
    volumes:
      - invoiceshelf_data:/data
      - invoiceshelf_conf:/conf
    networks:
      - invoiceshelf
    environment:
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8888
      - DB_CONNECTION=pgsql
      - DB_HOST=invoiceshelf_db
      - DB_PORT=5432
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=somepass
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost:8888
      - SANCTUM_STATEFUL_DOMAINS=localhost:8888
      - STARTUP_DELAY=
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    restart: unless-stopped
    depends_on:
      - invoiceshelf_db

networks:
  invoiceshelf:
    driver: bridge

volumes:
  postgres:
    driver: local

  invoiceshelf_data:
    driver: local

  invoiceshelf_conf:
    driver: local
```
