### ISSUE TITLE
Setup issue: Domain verification failed and unable to access via HAproxy.

### ISSUE THREAD

**Issue by erbmur** [InvoiceShelf/docker#24]
I have completed the installation of the docker version, and want to be able to access the app through my own domain invoices.mydomain.com.

I can access the installation via the ip:port, but when trying to access via my domain, I get the correct redirect to invoices.mydomain.com/installation, but just see a blank screen.  When attempting to complete the installation via the ip:port, I get to the domain verification screen at which point I keep getting the domain verification error.

My compose file is below, any help would be much appreciated!
```
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf
    container_name: invoiceshelf
    ports:
      - 90:80
    volumes:
      - /Portainer/InvoiceShelf/data:/data
      - /Portainer/InvoiceShelf/conf:/conf
    environment:
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=https://invoices.mydomain.com
      - DB_CONNECTION=mysql
      - DB_HOST=10.10.10.8
      - DB_PORT=49154
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=invoiceshelf
      - DB_PASSWORD_FILE=
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=mydomain.com
      - SANCTUM_STATEFUL_DOMAINS=mydomain.com
      - STARTUP_DELAY=
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    restart: unless-stopped
```
