### ISSUE TITLE
Website login validation error with domain

### ISSUE THREAD

**Issue by MrToast72** [InvoiceShelf/docker#26]
So I have an odd error when trying to login to my invoiceshelf setup. Simply put, if I put in my credentials and click login, I get an error :

`Please check your internet connection or wait until servers are back online.`

But if I just refresh the page, it will redirect me to my invoice.mydomain.com/admin/dashboard

I run Nginx Proxy Manager as a separate container to manage all my proxying, so best I can do is provide a screenshot of that :

<img width="500" alt="Screenshot 2024-11-20 at 09 35 46" src="https://github.com/user-attachments/assets/6576046e-830c-469c-ab03-fc563c07f0b4">

As well as a picture of the error its self :

<img width="1728" alt="Screenshot 2024-11-20 at 09 28 20" src="https://github.com/user-attachments/assets/4b2c8e7a-72be-4cc4-93fb-13de188a51a2">

and of course my docker compose file :

```
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:2.0.0
    container_name: invoiceshelf
    ports:
      - 6942:80
    volumes:
      - /NVMe-Pool/App-Data-Pool/invoiceshelf/data:/data
      - /NVMe-Pool/App-Data-Pool/invoiceshelf/conf:/conf
    networks:
      - invoiceshelf
    environment:
      - PHP_TZ=America/REDACTED
      - TIMEZONE=America/REDACTED
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=https://invoice.mydomain.com/
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/InvoiceShelf/database/database.sqlite # please don't touch this!
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=invoice.mydomain.com
      - SANCTUM_STATEFUL_DOMAINS=invoice.mydomain.com
      - STARTUP_DELAY=
    restart: unless-stopped

networks:
  invoiceshelf:
```

I have it set in my docker as https because setting it as http changes nothing and I use nginx for https traffic anyways.
