### ISSUE TITLE
Docker compose postgresql, database connection error

### ISSUE THREAD

**Issue by rioug** [InvoiceShelf/docker#44]
Hi there, 

I am trying to run Invoiceshelf with docker compose using the posgres variant, but invoiceshelf can't connect to the database. I checked the database was running and accepting connection, I can connect from my host OS using the username/password set up in the `docker-compose.yml` file. 
I tried using the following as "database host" :
- 127.0.0.1
- localhost
- invoiceshelf (docker network name)

my `docker-compose.yml` :

```
#-------------------------------------------
# InvoiceShelf PostgreSQL docker-compose variant
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  invoiceshelf_db:
    container_name: invoiceshelf_db
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=my_pass
      - POSTGRES_USER=invoiceshelf
      - POSTGRES_DB=invoiceshelf
    networks:
      - invoiceshelf
    restart: unless-stopped
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:latest
    container_name: invoiceshelf
    ports:
      - 90:80
    volumes:
      - ./invoiceshelf_pgsql/data:/data
      - ./invoiceshelf_pgsql/conf:/conf
    networks:
      - invoiceshelf
    environment: 
      - PHP_TZ=Australia/Melbourne
      - TIMEZONE=Australia/Melbourne
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:90
      - DB_CONNECTION=pgsql
      - DB_HOST=invoiceshelf_db
      - DB_PORT=5432
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=my_pass
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=localhost
      - SANCTUM_STATEFUL_DOMAINS=localhost:90
      - STARTUP_DELAY=10
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    restart: unless-stopped
    depends_on:
      - invoiceshelf_db

networks:
  invoiceshelf:

volumes:
  postgres:

```

Screenshot :

![Image](https://github.com/user-attachments/assets/d2686890-5d41-4487-9a8b-285dc5f0c2f2)

I ran in the same issue with the MySQL version, but I got the sqllite version to run.
