### ISSUE TITLE
[Bug] Asset Management broken?

### ISSUE THREAD

**Issue by Dschogo** [InvoiceShelf/docker#5]
**Describe the bug**
Updating user/company avatars uploads the files correctly to `/invoiceshelf/data/app/public/<asset_number>/<filename>` but the get request to `/storage/<asset_number>/<filename>` results in a 404.

**Expected behavior**
Return the (correct) asset.

**Additional info**
Seems to be related to [crater issue 1222](https://github.com/crater-invoice/crater/issues/1222)  and [crater PR 1226](https://github.com/crater-invoice/crater/pull/1226)

**Please complete the following information:**
- InvoiceShelf version: docker-compose (invoiceshelf/invoiceshelf:latest) - 1.1.0
- PHP version: bundled
- Database type and version: bundled

**Optional info**
- OS:  docker host: debian arm64
- Browser: Firefox

<details>
  <summary>docker-compose.yml</summary>

```yml
#-------------------------------------------
#  Docker Compose
#  - Darko Gjorgjijoski
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

version: '3'

services:
   invoiceshelf_db:
     container_name: invoiceshelf_db
     image: mariadb:10
     environment:
       - MYSQL_ROOT_PASSWORD=randompw
       - MYSQL_DATABASE=invoiceshelf
       - MYSQL_USER=invoiceshelf
       - MYSQL_PASSWORD=randompw
     expose: 
       - 3306
     volumes:
       - mysql:/var/lib/mysql
     networks:
       - invoiceshelf
     restart: unless-stopped

   invoiceshelf:
     image: invoiceshelf/invoiceshelf
     container_name: invoiceshelf
     ports:
       - 90:80
     volumes:
       - ./invoiceshelf/data:/data
     networks:
       - invoiceshelf
     environment:
       - PUID=1000
       - PGID=1000
       - USER=invoiceshelf
       - PHP_TZ=UTC
       - TIMEZONE=UTC
       - DB_CONNECTION=mysql
       - DB_HOST=invoiceshelf_db
       - DB_PORT=3306
       - DB_DATABASE=invoiceshelf
       - DB_USERNAME=invoiceshelf
       - DB_PASSWORD=randompw
       - STARTUP_DELAY=0
     restart: unless-stopped
     depends_on:
       - invoiceshelf_db

networks:
   invoiceshelf:

volumes:
    mysql:
```
</details>
